Wrapped tests that are running into a compiler bug in #if __GNUC__ < 7 blocks, as they are checking for parameter failure with large values.
What is happening is that large values are being stored in alignment
and size (both of which are size_t) which is triggering a warning like:
../tests/aligned_alloc.c:59:4: error: argument 2 value ‘9223372036854775808’ exceeds maximum object size 9223372036854775807 [-Werror=alloc-size-larger-than=] p = aligned_alloc(alignment, size);

9223372036854775808 is 0x8000000000000000, which fits into a
size_t, but the compiler warning checks it erronously via a *signed*
check, when it should do so using an *unsigned* check (because size_t
is unsigned), which would not generate an error because it does not
exceed the largest value that can fit in a size_t.